import math
n=1000
fd = []
fd.append(['√log4n', math.sqrt(math.log(n, 4))])
print(1)
fd.append(['(log2n)^log2n', math.log(n, 2)**math.log(n, 2)])
print(2)
fd.append(['(log2n)^2', math.log(n, 2)**2])
print(3)
fd.append(['n^log2n', n**math.log(n, 2)])
print(4)
fd.append(['n^2', n**2])
print(5)
fd.append(['√n', math.sqrt(n)])
print(6)
fd.append(['3^log2n', 3**math.log(n, 2)])
print(7)
fd.append(['log2(log2n)', math.log(math.log(n, 2))])
print(8)
fd.append(['log3n', math.log(n, 3)])
print(9)
fd.append(['n^√n', n**math.sqrt(n)])
print(10)
fd.append(['n/log5n', n/math.log(n, 5)])
print(11)
fd.append(['7^(log2n)', 7**math.log(n, 2)])
print(12)
fd.append(['2^n', 2**n])
print(13)
fd.append(['2^(3n)', 2**(3*n)])
print(14)
#fd['2^(2^n)'] = 2**(2**n)
print(15)
fd.append(['4^n', 4**n])
print(16)
fd.append(['log2(n!)', math.log(math.factorial(n), 2)])
print(17)
fd.append(['n!', math.factorial(n)])
fd.sort(key=lambda x: x[1])
print(fd)
for i in fd:
    print(i[0])
